"""Extract every word of user-facing copy from the built site into COPY.md.

Written so the copy can be edited as writing rather than as HTML. It reads
site/, not the templates, so what comes out is exactly what a visitor reads —
including text assembled from content/*.toml, which is invisible if you only
look at the templates.

    python builder.py && python export_copy.py

Each block is labelled with the file and the CSS selector it came from, so an
edit can be put back without hunting for it.
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SITE = ROOT / "site"
OUT = ROOT / "COPY.md"

PAGES = [("/", "index.html"), ("/story/", "story/index.html")]

# Elements whose text is read by a visitor, in document order. Anything not
# listed here is chrome.
BLOCKS = (
    "h1", "h2", "h3", "p", "li", "figcaption", "dt", "blockquote",
)

SKIP_INSIDE = ("nav", "footer", "script", "style", "head")


def strip_tags(fragment: str) -> str:
    fragment = re.sub(r"<br\s*/?>", " ", fragment, flags=re.I)
    fragment = re.sub(r"<[^>]+>", "", fragment)
    text = html.unescape(fragment)
    return re.sub(r"\s+", " ", text).strip()


def label_for(tag: str, attrs: str) -> str:
    match = re.search(r'class="([^"]+)"', attrs)
    if match:
        first = match.group(1).split()[0]
        return f"{tag}.{first}"
    match = re.search(r'id="([^"]+)"', attrs)
    if match:
        return f"{tag}#{match.group(1)}"
    return tag


def extract(html_text: str) -> list[tuple[str, str]]:
    # Drop the chrome wholesale before looking for text.
    body = html_text
    for tag in SKIP_INSIDE:
        body = re.sub(rf"<{tag}\b.*?</{tag}>", "", body, flags=re.S | re.I)

    out = []
    pattern = re.compile(rf"<({'|'.join(BLOCKS)})\b([^>]*)>(.*?)</\1>", re.S | re.I)
    for match in pattern.finditer(body):
        tag, attrs, inner = match.group(1).lower(), match.group(2), match.group(3)
        # Skip wrappers whose whole content is another block element.
        if re.match(rf"\s*<(?:{'|'.join(BLOCKS)})\b", inner, re.I):
            continue
        text = strip_tags(inner)
        if text:
            out.append((label_for(tag, attrs), text))
    return out


def main() -> int:
    if not SITE.is_dir():
        print("site/ does not exist — run: python builder.py", file=sys.stderr)
        return 1

    lines = [
        "# Every word on the site",
        "",
        "Generated by `export_copy.py` from the built site, so this is what a",
        "visitor actually reads, in the order they read it. Chrome — navigation,",
        "footer, button labels that are pure UI — is left out.",
        "",
        "**To edit:** change the text under any heading below and hand this file",
        "back. Each block is labelled with the element it came from so the edit",
        "can be applied without guesswork. Do not worry about the labels.",
        "",
        "Regenerate with `python builder.py && python export_copy.py`.",
        "",
    ]

    total = 0
    for url, relative in PAGES:
        page = SITE / relative
        if not page.exists():
            continue
        lines += ["---", "", f"## {url}", ""]
        for label, text in extract(page.read_text(encoding="utf-8")):
            lines += [f"`{label}`", "", text, ""]
            total += 1

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    words = sum(len(t.split()) for _, t in
                (b for _, rel in PAGES if (SITE / rel).exists()
                 for b in extract((SITE / rel).read_text(encoding="utf-8"))))
    print(f"{OUT.name}: {total} blocks, {words} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
